# Docker Compose file for development environment
name: docker-ceedd-project
services:
  ceedd-api:
    container_name: app-ceedd-api-container
    image: ghcr.io/vick25/app-ceedd-api
    build:
      context: .
      dockerfile: Dockerfile
    command: /app/entrypoint.sh
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
